### ISSUE TITLE
Really cool idea

### ISSUE THREAD

**Issue by rw86347** [Delafinn/GPT4ALLxPYTTSX3#1]
I am really wanting to play around with this on my Ubuntu box.  However something seems to be wrong with the speach engine.  I keep getting this error:  I am guessing I did not instal esp correctly but I have tried over and over.  Any ideas?

### Response:
 Once Upon A Time, there was a young girl named Cinderella who lived in the kingdom of Fairy Tales. She had a stepmother who was cruel and heartless, forcing her to work long hours in the kitchen and never allowing her to go out or have any fun. One day, Cinderella's fairy godmother appeared to her and told her that she was going on a grand adventure to the land of Never-Ending Story.
Once Upon A Time, Cinderella was a young girl who lived in the kingdom of Fairy Tales. She had a stepmother who was cruel and heartless, forcing her to work long hours in the kitchen and
Traceback (most recent call last):
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwilson/temp/LLM/g4a_voice.py", line 18, in <module>
    engine = pyttsx3.init()
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

**Comment by Delafinn** [comment]
I will start troubleshooting on my Linux machine tonight. I used my windows 10 machine for this script.

**Comment by Delafinn** [comment]
Could you verify that you have a compatible speech synthesis engine installed on your Linux machine? pyttsx3 relies on a speech synthesis engine, such as eSpeak or Festival, to convert text to speech.

Install a compatible speech synthesis engine by running the appropriate command for your Linux distribution. For example, on Ubuntu, you can install the espeak speech synthesis system using:

sudo apt update

sudo apt install espeak


Below is the code pointing me in this direction:

File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/drivers/espeak.py", line 5, in
from . import _espeak, toUtf8, fromUtf8
File "/home/rwilson/miniconda3/envs/tf/lib/python3.9/site-packages/pyttsx3/drivers/_espeak.py", line 18, in
dll = cdll.LoadLibrary('libespeak.so.1')



Let me know if that helps. I am running into many problems with my Linux device
